<<<<<<< HEAD
// *** PLACEHOLDER — Replace with the output of `flutterfire configure` ***
//
// To generate this file, run:
//   dart pub global activate flutterfire_cli
//   flutterfire configure
//
// This will configure Firebase for your app and write firebase_options.dart
// with your actual Google Services config.

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
=======
// File generated by firebase-setup.mjs — do not edit manually.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web — '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for iOS — '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macOS — '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows — '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for Linux — '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
>>>>>>> f87dab5 (Add request validation middleware to API server routes)
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

<<<<<<< HEAD
  // Replace with your actual Firebase Android config values:
  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'YOUR_API_KEY',
    appId: '1:YOUR_PROJECT_NUMBER:android:YOUR_APP_ID',
    messagingSenderId: 'YOUR_SENDER_ID',
    projectId: 'YOUR_PROJECT_ID',
    storageBucket: 'YOUR_PROJECT_ID.appspot.com',
=======
  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAHZZNfmBfeca1HQ2H2W6EjJAz1ovHCt6c',
    appId: '1:1015523956837:android:b74373bd62572b7a1b0e8c',
    messagingSenderId: '1015523956837',
    projectId: 'my-awesome-project-2d1b2',
    storageBucket: 'my-awesome-project-2d1b2.firebasestorage.app',
>>>>>>> f87dab5 (Add request validation middleware to API server routes)
  );
}
